language: node_js
node_js:
  - '4'
sudo: required
cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
before_install:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install -g codeclimate-test-reporter
install:
  - npm install
  - bower install
script:
  - (eval "$TEST_COMMAND")
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  code_climate:
    repo_token: asdf234asdfsdf
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
env:
  - 'TEST_COMMAND="COVERAGE=true ember try:one default"'
  - 'TEST_COMMAND="ember try:each"'
  - TEST_COMMAND="ALLOW_DEPRECATIONS=true ember try:each --config-path="config/scenarios/unstable.js"
